// Manual translations for navigation and UI elements
const commonTranslations = {
  'en': {
    'Home': 'Home',
    'About': 'About', 
    'News': 'News',
    'Events': 'Events',
    'Contact': 'Contact',
    'Admin': 'Admin',
    'Dashboard': 'Dashboard',
    'Welcome to your content management system': 'Welcome to your content management system',
    'Create News': 'Create News',
    'Create Event': 'Create Event',
    'Recent Content': 'Recent Content',
    'Send us a Message': 'Send us a Message',
    'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.': 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'Name': 'Name',
    'Email': 'Email',
    'Subject': 'Subject',
    'Message': 'Message',
    'Send Message': 'Send Message',
    'Modern CMS': 'Modern CMS',
    'A modern, minimalist website with integrated content management system for seamless content creation and management.': 'A modern, minimalist website with integrated content management system for seamless content creation and management.',
    'Quick Links': 'Quick Links',
    'Contact Info': 'Contact Info',
    'Email: info@example.com': 'Email: info@example.com',
    'Phone: +1 234 567 890': 'Phone: +1 234 567 890',
    'Address: 123 Main St, City': 'Address: 123 Main St, City',
    '© 2024 Modern CMS. All rights reserved.': '© 2024 Modern CMS. All rights reserved.',
    'News Management': 'News Management',
    'Manage your news articles and announcements': 'Manage your news articles and announcements',
    'Add News': 'Add News',
    'All News Articles': 'All News Articles',
    'Loading...': 'Loading...',
    'Published': 'Published',
    'Draft': 'Draft',
    'Featured': 'Featured',
    'No news articles found.': 'No news articles found.',
    'Events Management': 'Events Management',
    'Manage your events and activities': 'Manage your events and activities',
    'Add Event': 'Add Event',
    'All Events': 'All Events',
    'No events found.': 'No events found.',
    'Back to News': 'Back to News',
    'Edit News Article': 'Edit News Article',
    'Create News Article': 'Create News Article',
    'Article Details': 'Article Details',
    'Update the news article information': 'Update the news article information',
    'Enter the news article information': 'Enter the news article information',
    'Title': 'Title',
    'Excerpt': 'Excerpt',
    'Content': 'Content',
    'Image URL (optional)': 'Image URL (optional)',
    'External Link (optional)': 'External Link (optional)',
    'Category': 'Category',
    'Cancel': 'Cancel',
    'Saving...': 'Saving...',
    'Update Article': 'Update Article',
    'Create Article': 'Create Article',
    'Back to Events': 'Back to Events',
    'Edit Event': 'Edit Event',
    'Create Event': 'Create Event',
    'Event Details': 'Event Details',
    'Update the event information': 'Update the event information',
    'Enter the event information': 'Enter the event information',
    'Description': 'Description',
    'Date': 'Date',
    'Time': 'Time',
    'End Time (optional)': 'End Time (optional)',
    'Location': 'Location',
    'Update Event': 'Update Event',
    'Create Event': 'Create Event',
    'There\'s Never A Dull Moment In Our Town': 'There\'s Never A Dull Moment In Our Town',
    'From unforgettable musical performances to breathtaking art exhibitions. There is always something going on.': 'From unforgettable musical performances to breathtaking art exhibitions. There is always something going on.',
    'Check Out Upcoming Events': 'Check Out Upcoming Events',
      'Hello! Welcome to the website of Dimos Amathountas': 'Hello! Welcome to the website of Dimos Amathountas',
  'This website will allow you to learn more about the beautiful village of Amathountas.': 'This website will allow you to learn more about the beautiful village of Amathountas.',
    'See What\'s New': 'See What\'s New',
    'Explore Our Charming Little Town': 'Explore Our Charming Little Town',
    'Display a directory of businesses in your municipality with important contact details and opening hours.': 'Display a directory of businesses in your municipality with important contact details and opening hours.',
    'Open Town Map': 'Open Town Map',
    'Stay updated with our latest announcements and insights': 'Stay updated with our latest announcements and insights',
    'No featured news found.': 'No featured news found.',
    'No Image': 'No Image',
    'Continue reading': 'Continue reading',
    'View All News': 'View All News',
    'Event management is the application of project management to the creation and development of small and/or large-scale personal or corporate events.': 'Event management is the application of project management to the creation and development of small and/or large-scale personal or corporate events.',
    'No upcoming events found.': 'No upcoming events found.',
    'View All Events': 'View All Events',
    'Recent News': 'Recent News',
    'Total News': 'Total News',
    'Published articles': 'Published articles',
    'Total Events': 'Total Events',
    'Scheduled events': 'Scheduled events',
    'Latest news articles': 'Latest news articles',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'No recent news': 'No recent news',
    'Recent Events': 'Recent Events',
    'Latest events': 'Latest events',
    'No recent events': 'No recent events',
    'Admin Panel': 'Admin Panel',
    'Dashboard': 'Dashboard',
    'News': 'News',
    'Events': 'Events',
    'Settings': 'Settings',
    'Back to Website': 'Back to Website',
    'Create, edit, and manage news articles': 'Create, edit, and manage news articles',
    'Create, edit, and manage events': 'Create, edit, and manage events',
    'Search news...': 'Search news...',
    'Αναζήτηση ειδήσεων...': 'Αναζήτηση ειδήσεων...',
    'By': 'By',
    'Από': 'Από',
    'Read More / External Link': 'Read More / External Link',
    'Διαβάστε Περισσότερα / Εξωτερικός Σύνδεσμος': 'Διαβάστε Περισσότερα / Εξωτερικός Σύνδεσμος',
    'at': 'at',
    'στην': 'στην',
    'Event': 'Event',
    'Εκδήλωση': 'Εκδήλωση',
    'Upcoming Events': 'Upcoming Events',
    'Featured News': 'Featured News',
    'Image': 'Image',
    'Article Image': 'Article Image',
    'Event Image': 'Event Image',
    'Choose Image': 'Choose Image',
    'Uploading...': 'Uploading...',
    'Image Preview': 'Image Preview',
    'Click "Choose Image" to upload an image or enter a URL above': 'Click "Choose Image" to upload an image or enter a URL above',
    'Supported formats: JPG, PNG, GIF (max 5MB)': 'Supported formats: JPG, PNG, GIF (max 5MB)',
    'or drag and drop an image file': 'or drag and drop an image file',
    'Please select an image file': 'Please select an image file',
    'Image size must be less than 5MB': 'Image size must be less than 5MB',
    'Image uploaded successfully': 'Image uploaded successfully',
    'Failed to upload image': 'Failed to upload image',
    'Operating Hours: Monday – Friday 07:30 – 15:00': 'Operating Hours: Monday – Friday 07:30 – 15:00',
    // New translations for municipality pages
    'Municipality': 'Municipality',
    'Services': 'Services',
    'Citizen Services': 'Citizen Services',
    'Civil Marriages': 'Civil Marriages',
    'More': 'More',
    'Add New Page': 'Add New Page',
    'Edit Page': 'Edit Page',
    'Page Image': 'Page Image',
    'Slug (URL)': 'Slug (URL)',
    'Select a category': 'Select a category',
    'Select the category where this page will appear': 'Select the category where this page will appear',
    'English': 'English',
    'Greek': 'Greek',
    'Enter title in English': 'Enter title in English',
    'Εισάγετε τίτλο στα ελληνικά': 'Εισάγετε τίτλο στα ελληνικά',
    'Enter excerpt in English': 'Enter excerpt in English',
    'Εισάγετε περίληψη στα ελληνικά': 'Εισάγετε περίληψη στα ελληνικά',
    'Enter content in English': 'Enter content in English',
    'Εισάγετε περιεχόμενο στα ελληνικά': 'Εισάγετε περιεχόμενο στα ελληνικά',
    'Loading municipality pages...': 'Loading municipality pages...',
    'Loading services...': 'Loading services...',
    'Loading citizen services...': 'Loading citizen services...',
    'Loading civil marriages...': 'Loading civil marriages...',
    'No pages available': 'No pages available',
    'No services available': 'No services available',
    'No citizen services available': 'No citizen services available',
    'No civil marriages available': 'No civil marriages available',
    'Validation Error': 'Validation Error',
    'Please fill in all required fields': 'Please fill in all required fields',
    'A page with this slug already exists. Please choose a different slug.': 'A page with this slug already exists. Please choose a different slug.',
    'Success': 'Success',
    'Page created successfully': 'Page created successfully',
    'Page updated successfully': 'Page updated successfully',
    'Page deleted successfully': 'Page deleted successfully',
    'Error': 'Error',
    'Failed to load pages': 'Failed to load pages',
    'Failed to save page': 'Failed to save page',
    'Failed to delete page': 'Failed to delete page',
    'Page Information': 'Page Information',
    'Related Pages': 'Related Pages',
    'No related pages found': 'No related pages found',
    'Last Updated': 'Last Updated',
    'Municipality pages will appear here once they are added.': 'Municipality pages will appear here once they are added.',
    'Explore information about our Municipality, administration, services, and programs.': 'Explore information about our Municipality, administration, services, and programs.',
    'Pages Management': 'Pages Management',
    'Manage your municipality pages and content': 'Manage your municipality pages and content',
    'All Pages': 'All Pages',
    'Filter by Category': 'Filter by Category',
    'All Categories': 'All Categories',
    'Create Page': 'Create Page',
    'Update Page': 'Update Page',
    'Are you sure you want to delete this page?': 'Are you sure you want to delete this page?',
    'This action cannot be undone.': 'This action cannot be undone.',
    'Confirm Delete': 'Confirm Delete',
    'Enter a URL-friendly name (lowercase, hyphens instead of spaces)': 'Enter a URL-friendly name (lowercase, hyphens instead of spaces)',
    'e.g., about-us, contact-info, services-list': 'e.g., about-us, contact-info, services-list',
    'Optional': 'Optional',
    'Published': 'Published',
    'Unpublished': 'Unpublished',
    'Page Statistics': 'Page Statistics',
    'Total Pages': 'Total Pages',
    'Published Pages': 'Published Pages',
    'Draft Pages': 'Draft Pages',
    'Municipality Pages': 'Municipality Pages',
    'Services Pages': 'Services Pages',
    'Citizen Services Pages': 'Citizen Services Pages',
    'Civil Marriages Pages': 'Civil Marriages Pages',
    'Amathountas': 'Amathountas',
    'Museums': 'Museums'
  },
  'el': {
    'Home': 'Αρχική',
    'About': 'Σχετικά',
    'News': 'Νέα',
    'Events': 'Εκδηλώσεις', 
    'Contact': 'Επικοινωνία',
    'Admin': 'Διαχείριση',
    'Dashboard': 'Πίνακας Ελέγχου',
    'Welcome to your content management system': 'Καλώς ήρθατε στο σύστημα διαχείρισης περιεχομένου',
    'Create News': 'Δημιουργία Νέας',
    'Create Event': 'Δημιουργία Εκδήλωσης',
    'Recent Content': 'Πρόσφατο Περιεχόμενο',
    'Send us a Message': 'Στείλτε μας ένα Μήνυμα',
    'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.': 'Θα θέλαμε να ακούσουμε από εσάς. Στείλτε μας ένα μήνυμα και θα απαντήσουμε το συντομότερο δυνατό.',
    'Name': 'Όνομα',
    'Email': 'Email',
    'Subject': 'Θέμα',
    'Message': 'Μήνυμα',
    'Send Message': 'Αποστολή Μηνύματος',
    'Modern CMS': 'Σύγχρονο CMS',
    'A modern, minimalist website with integrated content management system for seamless content creation and management.': 'Μια σύγχρονη, μινιμαλιστική ιστοσελίδα με ενσωματωμένο σύστημα διαχείρισης περιεχομένου για απρόσκοπτη δημιουργία και διαχείριση περιεχομένου.',
    'Quick Links': 'Γρήγοροι Σύνδεσμοι',
    'Contact Info': 'Στοιχεία Επικοινωνίας',
    'Email: info@example.com': 'Email: info@example.com',
    'Phone: +1 234 567 890': 'Τηλέφωνο: +1 234 567 890',
    'Address: 123 Main St, City': 'Διεύθυνση: 123 Main St, City',
    '© 2024 Modern CMS. All rights reserved.': '© 2024 Σύγχρονο CMS. Όλα τα δικαιώματα διατηρούνται.',
    'News Management': 'Διαχείριση Νέας',
    'Manage your news articles and announcements': 'Διαχειριστείτε τα άρθρα και τις ανακοινώσεις σας',
    'Add News': 'Προσθήκη Νέας',
    'All News Articles': 'Όλα τα Άρθρα Νέας',
    'Loading...': 'Φόρτωση...',
    'Published': 'Δημοσιευμένο',
    'Draft': 'Πρόχειρο',
    'Featured': 'Προτεινόμενο',
    'No news articles found.': 'Δεν βρέθηκαν άρθρα νέας.',
    'Events Management': 'Διαχείριση Εκδηλώσεων',
    'Manage your events and activities': 'Διαχειριστείτε τις εκδηλώσεις και δραστηριότητές σας',
    'Add Event': 'Προσθήκη Εκδήλωσης',
    'All Events': 'Όλες οι Εκδηλώσεις',
    'No events found.': 'Δεν βρέθηκαν εκδηλώσεις.',
    'Back to News': 'Επιστροφή στη Νέα',
    'Edit News Article': 'Επεξεργασία Άρθρου Νέας',
    'Create News Article': 'Δημιουργία Άρθρου Νέας',
    'Article Details': 'Λεπτομέρειες Άρθρου',
    'Update the news article information': 'Ενημερώστε τις πληροφορίες του άρθρου νέας',
    'Enter the news article information': 'Εισάγετε τις πληροφορίες του άρθρου νέας',
    'Title': 'Τίτλος',
    'Excerpt': 'Περίληψη',
    'Content': 'Περιεχόμενο',
    'Image URL (optional)': 'URL Εικόνας (προαιρετικό)',
    'External Link (optional)': 'Εξωτερικός Σύνδεσμος (προαιρετικό)',
    'Category': 'Κατηγορία',
    'Cancel': 'Ακύρωση',
    'Saving...': 'Αποθήκευση...',
    'Update Article': 'Ενημέρωση Άρθρου',
    'Create Article': 'Δημιουργία Άρθρου',
    'Back to Events': 'Επιστροφή στις Εκδηλώσεις',
    'Edit Event': 'Επεξεργασία Εκδήλωσης',
    'Create Event': 'Δημιουργία Εκδήλωσης',
    'Event Details': 'Λεπτομέρειες Εκδήλωσης',
    'Update the event information': 'Ενημερώστε τις πληροφορίες της εκδήλωσης',
    'Enter the event information': 'Εισάγετε τις πληροφορίες της εκδήλωσης',
    'Description': 'Περιγραφή',
    'Date': 'Ημερομηνία',
    'Time': 'Ώρα',
    'End Time (optional)': 'Ώρα Τέλους (προαιρετικό)',
    'Location': 'Τοποθεσία',
    'Update Event': 'Ενημέρωση Εκδήλωσης',
    'Create Event': 'Δημιουργία Εκδήλωσης',
    'There\'s Never A Dull Moment In Our Town': 'Δεν υπάρχει ποτέ μια βαρετή στιγμή στην πόλη μας',
    'From unforgettable musical performances to breathtaking art exhibitions. There is always something going on.': 'Από αξέχαστες μουσικές παραστάσεις έως εντυπωσιακές καλλιτεχνικές εκθέσεις. Πάντα συμβαίνει κάτι.',
    'Check Out Upcoming Events': 'Δείτε τις επερχόμενες εκδηλώσεις',
    'Hello! Welcome to the website of Agios Athanasios Municipality': 'Γεια σας! Καλώς ήρθατε στην ιστοσελίδα του Δήμου Αγίου Αθανασίου',
    'This website will allow you to learn more about the beautiful village of Agios Athanasios.': 'Αυτή η ιστοσελίδα θα σας επιτρέψει να μάθετε περισσότερα για το όμορφο χωριό του Αγίου Αθανασίου.',
    'See What\'s New': 'Δείτε τι νέο υπάρχει',
    'Explore Our Charming Little Town': 'Εξερευνήστε την γοητευτική μας μικρή πόλη',
    'Display a directory of businesses in your municipality with important contact details and opening hours.': 'Εμφανίστε έναν κατάλογο επιχειρήσεων στον δήμο σας με σημαντικές λεπτομέρειες επικοινωνίας και ώρες λειτουργίας.',
    'Open Town Map': 'Άνοιγμα χάρτη πόλης',
    'Stay updated with our latest announcements and insights': 'Μείνετε ενημερωμένοι με τις τελευταίες μας ανακοινώσεις και πληροφορίες',
    'No featured news found.': 'Δεν βρέθηκαν προτεινόμενα νέα.',
    'No Image': 'Δεν υπάρχει εικόνα',
    'Continue reading': 'Συνέχεια ανάγνωσης',
    'View All News': 'Προβολή όλων των ειδήσεων',
    'Event management is the application of project management to the creation and development of small and/or large-scale personal or corporate events.': 'Η διαχείριση εκδηλώσεων είναι η εφαρμογή της διαχείρισης έργων στη δημιουργία και ανάπτυξη μικρών και/ή μεγάλων προσωπικών ή εταιρικών εκδηλώσεων.',
    'No upcoming events found.': 'Δεν βρέθηκαν επερχόμενες εκδηλώσεις.',
    'View All Events': 'Προβολή όλων των εκδηλώσεων',
    'Recent News': 'Πρόσφατες Ειδήσεις',
    'Total News': 'Σύνολο Ειδήσεων',
    'Published articles': 'Δημοσιευμένα άρθρα',
    'Total Events': 'Σύνολο Εκδηλώσεων',
    'Scheduled events': 'Προγραμματισμένες εκδηλώσεις',
    'Latest news articles': 'Τελευταία άρθρα ειδήσεων',
    'Edit': 'Επεξεργασία',
    'Delete': 'Διαγραφή',
    'No recent news': 'Δεν υπάρχουν πρόσφατες ειδήσεις',
    'Recent Events': 'Πρόσφατες Εκδηλώσεις',
    'Latest events': 'Τελευταίες εκδηλώσεις',
    'No recent events': 'Δεν υπάρχουν πρόσφατες εκδηλώσεις',
    'Admin Panel': 'Πίνακας Διαχείρισης',
    'Dashboard': 'Πίνακας Ελέγχου',
    'News': 'Νέα',
    'Events': 'Εκδηλώσεις',
    'Settings': 'Ρυθμίσεις',
    'Back to Website': 'Επιστροφή στην Ιστοσελίδα',
    'Create, edit, and manage news articles': 'Δημιουργήστε, επεξεργαστείτε και διαχειριστείτε άρθρα ειδήσεων',
    'Create, edit, and manage events': 'Δημιουργήστε, επεξεργαστείτε και διαχειριστείτε εκδηλώσεις',
    'Search news...': 'Αναζήτηση ειδήσεων...',
    'Αναζήτηση ειδήσεων...': 'Αναζήτηση ειδήσεων...',
    'By': 'Από',
    'Από': 'Από',
    'Read More / External Link': 'Διαβάστε Περισσότερα / Εξωτερικός Σύνδεσμος',
    'Διαβάστε Περισσότερα / Εξωτερικός Σύνδεσμος': 'Διαβάστε Περισσότερα / Εξωτερικός Σύνδεσμος',
    'at': 'στην',
    'στην': 'στην',
    'Event': 'Εκδήλωση',
    'Εκδήλωση': 'Εκδήλωση',
    'Upcoming Events': 'Επερχόμενες Εκδηλώσεις',
    'Featured News': 'Προτεινόμενα Νέα',
    'Image': 'Εικόνα',
    'Article Image': 'Εικόνα Άρθρου',
    'Event Image': 'Εικόνα Εκδήλωσης',
    'Choose Image': 'Επιλογή Εικόνας',
    'Uploading...': 'Φορτώνεται...',
    'Image Preview': 'Προεπισκόπηση Εικόνας',
    'Click "Choose Image" to upload an image or enter a URL above': 'Κάντε κλικ στο "Επιλογή Εικόνας" για να ανεβάσετε μια εικόνα ή εισάγετε μια διεύθυνση URL παραπάνω',
    'Supported formats: JPG, PNG, GIF (max 5MB)': 'Υποστηριζόμενες μορφές: JPG, PNG, GIF (μέγιστο 5MB)',
    'or drag and drop an image file': 'ή σύρετε και αφήστε μια αρχείο εικόνας',
    'Please select an image file': 'Παρακαλώ επιλέξτε ένα αρχείο εικόνας',
    'Image size must be less than 5MB': 'Το μέγεθος της εικόνας πρέπει να είναι μικρότερο από 5MB',
    'Image uploaded successfully': 'Η εικόνα ανέβηκε επιτυχώς',
    'Failed to upload image': 'Απέτυχε η ανάβαση της εικόνας',
    'Operating Hours: Monday – Friday 07:30 – 15:00': 'Ώρες λειτουργίας: Δευτέρα – Παρασκευή 07:30 – 15:00',
    // New translations for municipality pages
    'Municipality': 'Δήμος',
    'Services': 'Υπηρεσίες',
    'Citizen Services': 'Υπηρεσίες Πολίτη',
    'Civil Marriages': 'Γάμοι',
    'More': 'Περισσότερα',
    'Add New Page': 'Προσθήκη Νέας Σελίδας',
    'Edit Page': 'Επεξεργασία Σελίδας',
    'Page Image': 'Εικόνα Σελίδας',
    'Slug (URL)': 'Slug (URL)',
    'Select a category': 'Επιλέξτε κατηγορία',
    'Select the category where this page will appear': 'Επιλέξτε την κατηγορία στην οποία θα εμφανίζεται αυτή η σελίδα',
    'English': 'Αγγλικά',
    'Greek': 'Ελληνικά',
    'Enter title in English': 'Εισάγετε τίτλο στα Αγγλικά',
    'Εισάγετε τίτλο στα ελληνικά': 'Εισάγετε τίτλο στα ελληνικά',
    'Enter excerpt in English': 'Εισάγετε περίληψη στα Αγγλικά',
    'Εισάγετε περίληψη στα ελληνικά': 'Εισάγετε περίληψη στα ελληνικά',
    'Enter content in English': 'Εισάγετε περιεχόμενο στα Αγγλικά',
    'Εισάγετε περιεχόμενο στα ελληνικά': 'Εισάγετε περιεχόμενο στα ελληνικά',
    'Loading municipality pages...': 'Φόρτωση σελίδων δήμου...',
    'Loading services...': 'Φόρτωση υπηρεσιών...',
    'Loading citizen services...': 'Φόρτωση υπηρεσιών πολίτη...',
    'Loading civil marriages...': 'Φόρτωση γάμων...',
    'No pages available': 'Δεν υπάρχουν σελίδες δημού',
    'No services available': 'Δεν υπάρχουν υπηρεσίες',
    'No citizen services available': 'Δεν υπάρχουν υπηρεσίες πολίτη',
    'No civil marriages available': 'Δεν υπάρχουν γάμοι',
    'Validation Error': 'Σφάλμα Επικύρωσης',
    'Please fill in all required fields': 'Παρακαλώ συμπληρώστε όλα τα υποχρεωτικά πεδία',
    'A page with this slug already exists. Please choose a different slug.': 'Μια σελίδα με αυτόν τον slug υπάρχει ήδη. Παρακαλώ επιλέξτε έναν διαφορετικό slug.',
    'Success': 'Επιτυχία',
    'Page created successfully': 'Η σελίδα δημιουργήθηκε επιτυχώς',
    'Page updated successfully': 'Η σελίδα ενημερώθηκε επιτυχώς',
    'Page deleted successfully': 'Η σελίδα διαγράφηκε επιτυχώς',
    'Error': 'Σφάλμα',
    'Failed to load pages': 'Απέτυχε η φόρτωση των σελίδων',
    'Failed to save page': 'Απέτυχε η αποθήκευση της σελίδας',
    'Failed to delete page': 'Απέτυχε η διαγραφή της σελίδας',
    'Page Information': 'Πληροφορίες Σελίδας',
    'Related Pages': 'Σχετικές Σελίδες',
    'No related pages found': 'Δεν βρέθηκαν σχετικές σελίδες',
    'Last Updated': 'Τελευταία Ενημέρωση',
    'Municipality pages will appear here once they are added.': 'Οι σελίδες του δήμου θα εμφανίζονται εδώ μόλις προστεθούν.',
    'Explore information about our Municipality, administration, services, and programs.': 'Εξερευνήστε πληροφορίες για τον Δήμο μας, την διαχείριση, τις υπηρεσίες και τα προγράμματα μας.',
    'Pages Management': 'Διαχείριση Σελίδων',
    'Manage your municipality pages and content': 'Διαχειριστείτε τις σελίδες και το περιεχόμενο του δήμου σας',
    'All Pages': 'Όλες οι Σελίδες',
    'Filter by Category': 'Φιλτράρισμα κατηγορίας',
    'All Categories': 'Όλες οι Κατηγορίες',
    'Create Page': 'Δημιουργία Σελίδας',
    'Update Page': 'Ενημέρωση Σελίδας',
    'Are you sure you want to delete this page?': 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή τη σελίδα?',
    'This action cannot be undone.': 'Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    'Confirm Delete': 'Επιβεβαίωση Διαγραφής',
    'Enter a URL-friendly name (lowercase, hyphens instead of spaces)': 'Εισάγετε ένα URL-friendly όνομα (μικρά γράμματα, υπογράμμισμα αντί για κενά)',
    'e.g., about-us, contact-info, services-list': 'π.χ., about-us, contact-info, services-list',
    'Optional': 'Προαιρετικό',
    'Published': 'Δημοσιευμένο',
    'Unpublished': 'Μη Δημοσιευμένο',
    'Page Statistics': 'Στατιστικές Σελίδας',
    'Total Pages': 'Σύνολο Σελίδων',
    'Published Pages': 'Δημοσιευμένες Σελίδες',
    'Draft Pages': 'Πρόχειρες Σελίδες',
    'Municipality Pages': 'Σελίδες Δήμου',
    'Services Pages': 'Σελίδες Υπηρεσιών',
    'Citizen Services Pages': 'Σελίδες Υπηρεσιών Πολίτη',
    'Civil Marriages Pages': 'Σελίδες Γάμων',
    'Agios Athanasios': 'Άγιος Αθανάσιος',
    'Museums': 'Μουσεία'
  }
};

export function translateText(text, sourceLang = 'en', targetLang = 'el') {
  if (!text || text.trim() === '') {
    return text;
  }

  // Check common translations first
  if (commonTranslations[targetLang] && commonTranslations[targetLang][text]) {
    return commonTranslations[targetLang][text];
  }
  
  // For now, return original text if no translation found
  return text;
}

// Batch translate multiple texts
export async function translateBatch(texts, sourceLang = 'en', targetLang = 'el') {
  if (!Array.isArray(texts) || texts.length === 0) {
    return texts;
  }

  return texts.map(text => translateText(text, sourceLang, targetLang));
} 